### ISSUE TITLE
Help , HTTP over TCP tunnel

### ISSUE THREAD

**Issue by ingnelson** [zapling/golang-proxy#1]
Hello @zapling  

I am from America, is it  possible with your knowledge create a HTTP over TCP tunnel to bypass my isp provider , but any data the client need to transfer to the server should be via a new HTTP request ( encode64 ) then server decode the data  ? 
because my ISP provider blocks the upstream data via HTTP BODY.

It is difficul for me and i can not do it.
i did all the test to check the isp restrictions.

my telegram is : @Trader_Nelson

i will wait your reply.

**Comment by zapling** [comment]
@ingnelson Hi, unfortunately this is out of my expertise.
